create table if not exists public.wedding_tables (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

alter table public.guests
  add column if not exists table_id bigint references public.wedding_tables(id) on delete set null;

create index if not exists guests_table_id_idx on public.guests (table_id);

create or replace function public.validate_wedding_table_capacity()
returns trigger
language plpgsql
as $$
declare
  occupied_seats integer;
begin
  if new.table_id is null then
    return new;
  end if;

  select coalesce(sum(passes_number), 0)::integer
    into occupied_seats
    from public.guests
   where table_id = new.table_id
     and id <> new.id;

  if occupied_seats + new.passes_number > 10 then
    raise exception 'No hay suficientes puestos en esta mesa';
  end if;

  return new;
end;
$$;

drop trigger if exists guests_table_capacity_trigger on public.guests;

create trigger guests_table_capacity_trigger
before insert or update of table_id, passes_number on public.guests
for each row execute function public.validate_wedding_table_capacity();