alter table public.guests
  add column if not exists is_abroad boolean not null default false;

create table if not exists public.invitation_message_templates (
  id integer generated by default as identity primary key,
  template_type text not null unique check (template_type in ('standard', 'abroad')),
  content text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.invitation_message_templates (template_type, content)
values
  ('standard', 'Familiares aquí:

Hay momentos en la vida que son inolvidables, pero compartirlos con quienes amamos los hace eternos.❤️✨

No hay nada que nos haga más felices que unir nuestras vidas en matrimonio y queremos celebrarlo rodeados de las personas que más queremos y que han sido parte de nuestra historia. 💒💍

🗓 Fecha: 29 de Diciembre 2026
⏰ Hora: 5:30 pm 

🔗En el siguiente enlace pueden ver la invitación con todos los detalles de nuestra boda: {{url}}

🎟 *Número de Pases :* {{pases}}

Por favor, entren a confirmar su asistencia en el enlace lo antes posible para organizar todo de la mejor manera. ¡Los esperamos! 🥂🎉

📸 *Álbum de fotos compartido:* También hemos creado un álbum digital para recopilar los mejores momentos. Pueden ver las fotos y subir las que ustedes mismos tomen durante el evento aquí: 🔗 
{{album_url}}

Gracias por ser parte de este momento tan especial ❤️Un abrazo enorme lo queremos mucho 🫶🏻 *Néstor Quiñones y Valentina Moreno.*'),
  ('abroad', 'Mensaje para familiares y amigos en el extranjero


Hay momentos en la vida que son inolvidables, pero compartirlos con quienes amamos los hace eternos.❤️✨

Aunque la distancia nos separe en este día, sus nombres y su cariño siempre están presentes en nuestra historia. Nos haría muy felices que nos acompañen de corazón y a la distancia a unir nuestras vidas en matrimonio. 💒💍

🗓️ Fecha: 29 de Diciembre de 2026 ⏰ Hora: 5:30 pm (Hora de Venezuela)

🔗 En el siguiente enlace pueden ver nuestra invitación digital con todos los detalles de la boda: {{url}}

Queremos que vivan cada segundo de nuestro gran día con nosotros, sin importar dónde se encuentren.

📸 Álbum de fotos compartido: También hemos creado un álbum digital para recopilar los mejores momentos. Pueden ver las fotos y subir las que ustedes mismos tomen durante el evento aquí: 🔗{{album_url}}

¡Un abrazo enorme, los queremos muchísimo! 🫶🏻 Néstor Quiñones y Valentina Moreno')
on conflict (template_type) do nothing;
