create table if not exists public.guest_members (
  id bigint generated by default as identity primary key,
  guest_id bigint not null references public.guests(id) on delete cascade,
  name text not null,
  table_id bigint references public.wedding_tables(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists guest_members_guest_id_idx on public.guest_members (guest_id);
create index if not exists guest_members_table_id_idx on public.guest_members (table_id);

create or replace function public.validate_guest_member_capacity()
returns trigger
language plpgsql
as $$
declare
  allowed_passes integer;
  registered_members integer;
begin
  select passes_number into allowed_passes from public.guests where id = new.guest_id;
  select count(*)::integer into registered_members
    from public.guest_members
   where guest_id = new.guest_id
     and id <> new.id;

  if registered_members >= coalesce(allowed_passes, 0) then
    raise exception 'Esta invitación ya tiene registrados todos sus pases';
  end if;

  return new;
end;
$$;

drop trigger if exists guest_members_capacity_trigger on public.guest_members;

create trigger guest_members_capacity_trigger
before insert or update of guest_id on public.guest_members
for each row execute function public.validate_guest_member_capacity();

create or replace function public.validate_guest_member_table_capacity()
returns trigger
language plpgsql
as $$
declare
  occupied_seats integer;
begin
  if new.table_id is null then
    return new;
  end if;

  select count(*)::integer into occupied_seats
    from public.guest_members
   where table_id = new.table_id
     and id <> new.id;

  if occupied_seats >= 10 then
    raise exception 'No hay suficientes puestos en esta mesa';
  end if;

  return new;
end;
$$;

drop trigger if exists guest_members_table_capacity_trigger on public.guest_members;

create trigger guest_members_table_capacity_trigger
before insert or update of table_id on public.guest_members
for each row execute function public.validate_guest_member_table_capacity();